// eslint-disable-next-line import/no-anonymous-default-export
export default [{
        id: 1,
        name: "My First ",
        num: "25 April 2018",
        price: 89,
        img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 2,
        name: "108 Panchatantra Stories",
        num: " 1 September 2020",
        price: 98,
        img: "https://m.media-amazon.com/images/I/71rmxx8P2qL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 3,
        name: "Amazing Questions & Answers Science",
        num: "25 November 2018",
        price: 143,
        img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 4,
        name: "My First Book of Pencil Control",
        num: "25 April 2018",
        price: 57,
        img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 5,
        name: "My First 1000 Words",
        num: " 1 January 2018",
        price: 149,
        img: "https://m.media-amazon.com/images/I/71O-FI7QApL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 6,
        name: "101 Panchatantra Stories for Children",
        num: "30 September 2020",
        price: 135,
        img: "https://m.media-amazon.com/images/I/9173YBkMIsL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 7,
        name: "Pre-School Activities Pack ",
        num: "1 January 2021",
        price: 693,
        img: "https://m.media-amazon.com/images/I/913sv4sex3L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 8,
        name: "Early Learning Library Pack 1",
        num: "6 December 2020",
        price: 289,
        img: "https://m.media-amazon.com/images/I/71xMttNhr7L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 9,
        name: "Blossom Moral Story Book for Kids ",
        num: "7 December 2020",
        price: 80,
        img: "https://m.media-amazon.com/images/I/7122h3jWvEL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 10,
        name: "Brain Activity Book for Kids",
        num: "1 September 2021",
        price: 86,
        img: "https://m.media-amazon.com/images/I/7175YpTSa7L._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 11,
        name: "Willy the Silly Panda",
        num: "14 December 2021",
        price: 120,
        img: "https://m.media-amazon.com/images/I/71-ocPGQIJL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
    {
        id: 12,
        name: "Grandma's Bag of Stories",
        num: "1 January 2015",
        price: 157,
        img: "https://m.media-amazon.com/images/I/81jv44QdNwL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
    },
];